In [17]:
import os
import pandas as pd
import datetime

folder_path = '../DATA/ENERSHARE_DATA _NTUA'
prefix = 'Flows'

# Open all folders that start with 'Flows'
for foldername in os.listdir(folder_path):
    if foldername.startswith(prefix):
        file_path = folder_path
        file_path = os.path.join(folder_path, foldername)
        # Open all excel files from those folders
        for filename in os.listdir(file_path):
            temp_filename = os.path.join(file_path, filename)
            df = pd.read_excel(temp_filename, engine='xlrd' if filename.endswith('.xls') else 'openpyxl')
            #print(filename)
            #print(df.head())
            print(df.columns)
            #print(df['Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)'][1:26])
            #print(df['Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)'])
            
            #Here is some code to isolate the dates and merge them with timestamps
            '''
            print(df['Date'][0].date())
            for t in df['Date'][2:]:
                if type(t) is datetime.datetime:
                    print(df['Date'][0].combine(df['Date'][0].date(), t.time()))
            '''

Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47',
       'Unnamed: 48'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')

Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47',
       'Unnamed: 48'],
      dtype='object')

Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44'],
      dtype='object')

Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46'],
      dtype='object')
Index(['Unnamed: 0', 'Date',
       'Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44'],
      dtype='object')

InvalidFileException: openpyxl does not support .xls# file format, please check you can open it with Excel first. Supported formats are: .xlsx,.xlsm,.xltx,.xltm

In [12]:
import os
import pandas as pd
from openpyxl import load_workbook

folder_path = '../DATA/ENERSHARE_DATA _NTUA'
prefix = 'Flows'

# Open all folders that start with 'Flows'
for foldername in os.listdir(folder_path):
    if foldername.startswith(prefix):
        file_path = folder_path
        file_path = os.path.join(folder_path, foldername)
        # Open all excel files from those folders
        print(file_path)
        for filename in os.listdir(file_path):
             if filename.endswith('.xls') or filename.endswith('.xlsx'):
                # check if the file extension is .xls or .xlsx
                temp_file_path = os.path.join(file_path, filename)
                # read all sheets in the Excel file into a dictionary of dataframes
                if filename.endswith('.xls'):
                    dfs_dict = pd.read_excel(temp_file_path, sheet_name=None, engine='xlrd')
                else:
                    dfs_dict = pd.read_excel(temp_file_path, sheet_name=None, engine='openpyxl')
                # concatenate all dataframes into a single dataframe
                df = pd.concat(dfs_dict.values(), ignore_index=True)
                # do something with the dataframe
                print(df.head())

../DATA/ENERSHARE_DATA _NTUA/Flows 2016 - Hourly - Excel
     Unnamed: 0                 Date  \
0           NaN  2016-05-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                                  0
3                                                  0
4                                                  0

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2        1806.4    1061.82         NaN
3       1383.59    1062.41         NaN
4       1197.51    1062.15         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                                  0
3                                                  0
4                                                  0

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     433.148              0         86.8998  ...     2.22277     154.273
3     432.006              0         81.6923  ...     2.02587     152.993
4     431.434              0         55.7734  ...     2.02823     154.201

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0    0.160556      17.266     9.65455          3.56186
3             0           0     17.2652     10.1042          1.69306
4             0           0     17.0268      9.9666          1.52765

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            4.27423    0.746667     2.32889
3            2.03168     9.04889     1.85111
4            1.83318     11.3067           0

[5 rows x 47 columns]
     Unnamed: 0                 Date  \
0           NaN  2016-09-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                            3147.72
3                                            2384.96
4                                            2392.43

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       1181.61    1865.99         NaN
3       1190.74    2101.45         NaN
4       1215.25    2110.11         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                           0.533539
3                                            2.18186
4                                            2.04017

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     421.373        538.124          50.425  ...     9.54073     310.268
3     422.223        618.029         48.5337  ...      9.9283     287.198
4     422.397        615.254         48.0208  ...     9.69286     287.232

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     9.15222      135.05     5.19756          3.93637
3             0     8.53417     124.775     4.95928          6.79202
4             0     8.75361     124.858     4.88293          4.39261

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            5.52682     11.6167    0.353333
3            7.81082     14.0156     1.69778
4             5.0515     13.4822     1.44444

[5 rows x 47 columns]
     Unnamed: 0                 Date  \
0           NaN  2016-04-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                                  0
3                                                  0
4                                                  0

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2        2255.1    1057.21         NaN
3       2301.51    1061.57         NaN
4       2301.36     1065.2         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            7.16483
3                                            6.49186
4                                             4.2752

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     434.098              0         108.802  ...     14.6296     152.877
3     432.497              0         112.316  ...     14.2615     157.151
4     430.434              0         110.184  ...     13.5367     166.928

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     14.4356      138.21      14.095          7.32227
3             0     13.9022      135.69     13.2022          6.37551
4             0     14.2933      128.95     13.4102          5.70476

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            8.78673     23.6089     10.9133
3            7.65062     22.1333     8.12667
4            6.84572     24.0889     9.29778

[5 rows x 47 columns]

     Unnamed: 0                 Date  \
0           NaN  2016-01-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                                  0
3                                            646.419
4                                            1149.57

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       5023.68    1021.98         NaN
3       5043.94    1022.08         NaN
4       5110.92    1024.96         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                           0.532233
3                                           0.863352
4                                           0.560429

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     440.205              0         89.8208  ...     15.8227     286.088
3     440.672              0         91.2245  ...     17.4004     270.115
4      442.06              0         88.3812  ...     18.4008     259.484

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     5.04889     34.3277     13.3133          7.20137
3       10.2332     4.51556     35.2163     16.1743          4.51979
4       12.3508     6.02667     37.0513     16.0584           6.4701

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            8.64165     42.8089     39.3382
3            5.42375     46.7911     39.7372
4            7.76412     46.8622     38.7287

[5 rows x 47 columns]
     Unnamed: 0                 Date  \
0           NaN  2016-02-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                            518.687
3                                            520.396
4                                            621.366

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       1557.76          0         NaN
3       2349.34          0         NaN
4       2792.13          0         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            6.95333
3                                            7.44676
4                                            5.15948

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     437.486         771.32         92.1337  ...     16.0303     40.5495
3       436.9        782.119         91.7453  ...     16.2485     35.1467
4     436.621        814.158         87.7815  ...     14.8644     41.8603

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     13.1378     136.718     7.20142          3.57659
3             0     13.8667     141.401     8.71564          5.29819
4             0     12.8178     147.236     9.47973          3.74531

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            5.93425     42.0267     21.2203
3            5.82801     39.8222     21.7057
4            6.11984     39.5378      16.147

[5 rows x 47 columns]
     Unnamed: 0                 Date  \
0           NaN  2016-12-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                            2753.87
3                                            3411.89
4                                            3360.03

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       4269.57    1074.41         NaN
3       4343.44    1072.07         NaN
4       4396.79    1072.76         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            1.32725
3                                                  0
4                                            1.26542

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ...   Unnamed: 39 Unnamed: 40  \
0         NaN            NaN             NaN  ...           NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...  MOTOR OIL II      XANTHI
2     383.073        824.012         83.2467  ...       10.6656     14.3242
3      380.86        844.643         84.4264  ...       12.7039     13.9603
4     398.295        847.828         85.7273  ...       24.1361     12.4631

  Unnamed: 41 Unnamed: 42      Unnamed: 43        Unnamed: 44 Unnamed: 45  \
0         NaN         NaN              NaN                NaN         NaN
1    OINOFYTA       PLATY  SALFA ANTHOUSSA  SALFA ANO LIOSSIA      SERRES
2     173.848     26.1958          6.78901            7.80736     41.4061
3     148.619     21.0825          3.16238            5.63673     52.9403
4     152.463      16.249          6.36878             7.3241      51.795

  Unnamed: 46 Unnamed: 47 Unnamed: 48
0         NaN         NaN         NaN
1     TRIKALA         NaN         NaN
2     43.8462  169.224843       0.499
3      41.623  164.440504       0.320
4     38.9204  159.495931       0.377

[5 rows x 49 columns]

     Unnamed: 0                 Date  \
0           NaN  2016-06-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                                  0
3                                                  0
4                                                  0

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       3339.86    1068.58         NaN
3       3569.19     1072.2         NaN
4       3528.69    1070.15         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            10.2122
3                                            9.52259
4                                            9.48068

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     430.833        830.943         121.678  ...     10.6444  0.00238581
3     430.863        837.254         121.482  ...     9.88448           0
4     430.662        833.046         126.057  ...     10.3254           0

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2       3.73609     8.58028     152.743     8.77884          6.24435
3        11.029     9.56806     136.539     8.45593          5.61482
4       9.96719     10.3114     122.619      6.6261          6.41677

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            6.86879     3.78667     3.66667
3            6.17631     11.3956     2.96667
4            7.05844     12.6578     3.65333

[5 rows x 47 columns]
     Unnamed: 0                 Date  \
0           NaN  2016-03-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                            2132.33
3                                            2123.21
4                                            2101.19

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       1564.85    227.224         NaN
3       1642.07    244.935         NaN
4        1643.7    244.236         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            1.34212
3                                             1.3514
4                                            1.33356

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     434.078              0         101.946  ...     13.1777     50.9991
3      433.61              0         106.903  ...     12.4125      65.623
4       433.2              0         107.621  ...     13.1116     58.1874

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2       787.113     13.2622     137.658     9.39513          6.56309
3       798.583     12.4978     136.845     7.45043           4.8865
4       810.672     10.4889     140.789     6.96814          5.85573

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2             7.2194     31.0044     18.7022
3            5.37515     27.4489     18.5267
4             6.4413     24.2489     16.8756

[5 rows x 47 columns]
     Unnamed: 0                 Date  \
0           NaN  2016-08-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                            2170.93
3                                            1237.63
4                                            1216.66

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       4222.07    1027.79         NaN
3       4002.56    1063.68         NaN
4       4020.54    1064.55         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            8.61184
3                                            7.31037
4                                            6.43572

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     426.526        615.156         88.1702  ...       7.197     246.275
3     425.251        612.879         85.3534  ...     8.15696     252.163
4     420.463        603.154         85.8721  ...     8.46041     263.563

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     9.14917      113.63    0.305037          3.99546
3             0     9.23472     126.734           0          6.30911
4             0     9.22889     123.845    0.010467          3.82829

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            5.39501     10.4033     1.55556
3            6.94002     9.31861     1.58667
4            5.21112     10.3794        1.72

[5 rows x 47 columns]

     Unnamed: 0                 Date  \
0           NaN  2016-10-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                                  0
3                                                  0
4                                                  0

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       4070.83    867.035         NaN
3        3938.6    834.257         NaN
4       3933.76    837.138         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                           0.545717
3                                           0.541657
4                                           0.544294

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     434.319        762.192         88.0132  ...     9.38916     399.404
3      434.34        739.266         89.3353  ...     9.12587     370.962
4     429.441         742.49         85.4599  ...     8.15033     361.631

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     4.59694     97.6393     145.364          5.23932
3             0     5.10806     105.636     142.925          7.47413
4             0     4.98333     113.091     144.683          3.73247

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            6.28718     2.94889    0.562222
3            8.96896     2.72417     2.06667
4            5.47896     11.7553        2.34

[5 rows x 47 columns]
     Unnamed: 0                 Date  \
0           NaN  2016-07-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                            1503.89
3                                            1507.65
4                                            1502.26

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       3533.88     689.34         NaN
3       3523.37    633.456         NaN
4       3591.33    631.435         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                           0.580585
3                                           0.634376
4                                           0.428901

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     435.186        625.929         93.7363  ...       9.545     52.9801
3     447.641        638.384         89.8193  ...       9.897     42.8026
4     439.399        630.142         95.2913  ...       9.564     43.4879

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2       702.935      12.858     135.975     7.87864            4.983
3       709.044      12.691      145.31     7.81725            6.626
4        720.53      12.651     155.336      15.931            4.148

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            5.73045      11.851       2.315
3             7.6199      13.597       2.689
4             4.7702      12.512       2.145

[5 rows x 47 columns]
../DATA/ENERSHARE_DATA _NTUA/Flows 2017 - Hourly- Excel
     Unnamed: 0                 Date  \
0           NaN  2017-10-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 08:00:00
3  41487.416667  2013-08-01 09:00:00
4  41487.458333  2013-08-01 10:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                        1.21532e+06
3                                             468558
4                                             509195

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2   2.79415e+06     453971         NaN
3   3.31537e+06     456649         NaN
4   3.29663e+06     455963         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            1745.31
3                                            1057.84
4                                            857.591

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2      427927         521298         93556.9  ...     3918.68      380373
3      426998         533052         89671.5  ...     3986.91      382788
4      426516         449059         89887.6  ...     3907.21      373019

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0      3957.5     94770.9      142617             6385
3             0     3628.33       80782      136881             2869
4             0     2896.39     77390.5      134918             1482

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2             8300.5     276.667     2445.19
3             3729.7     750.556     3435.22
4             1926.6     8474.44     3457.25

[5 rows x 47 columns]

     Unnamed: 0                 Date  \
0           NaN  2017-07-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 08:00:00
3  41487.416667  2013-08-01 09:00:00
4  41487.458333  2013-08-01 10:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                        2.41625e+06
3                                             530001
4                                             507199

     Unnamed: 3   Unnamed: 4  Unnamed: 5  \
0           NaN          NaN         NaN
1  SIDIROKASTRO         KIPI         NaN
2   3.15759e+06  1.01559e+06         NaN
3   4.37103e+06  1.06393e+06         NaN
4   4.45483e+06  1.05937e+06         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            1635.58
3                                            850.482
4                                             2826.2

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 38   Unnamed: 39  \
0         NaN            NaN             NaN  ...         NaN           NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...   MOTOR OIL  MOTOR OIL II
2      423656        16226.5           77668  ...      197435             0
3      428499         341104         81661.8  ...      195399             0
4      412151         400877         81573.2  ...      192420        319.17

  Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43        Unnamed: 44  \
0         NaN         NaN         NaN              NaN                NaN
1      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA  SALFA ANO LIOSSIA
2     2826.94     92589.6     5729.57          1631.17            2120.52
3     3809.44     93618.4     5548.75          5867.27            7627.45
4     3994.44      108175     5719.39          5262.43            6841.16

  Unnamed: 45 Unnamed: 46  \
0         NaN         NaN
1      SERRES     TRIKALA
2     653.611     1588.14
3     1416.67     2454.99
4     7169.44     2000.12

  Relative Exit Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

[5 rows x 48 columns]
     Unnamed: 0                 Date  \
0           NaN  2017-05-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                                  0
3                                                  0
4                                                  0

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       2171.23    680.906         NaN
3       2653.84    577.747         NaN
4       2672.18    574.674         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                           0.659721
3                                           0.654448
4                                           0.641804

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     426.328              0         84.3508  ...     3.73662     375.517
3     426.361              0         86.2877  ...     3.57444     356.221
4     426.024              0         86.5186  ...     3.84307     359.339

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0           0     70.0752       13.09          3.75886
3             0           0     79.3216     11.4037        0.0217516
4             0           0     97.7828     11.3567          3.05271

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            4.69857     1.24972     3.76237
3          0.0271895     1.96167       4.473
4            3.81589     3.56389     3.55829

[5 rows x 47 columns]
     Unnamed: 0                 Date  \
0           NaN  2017-08-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 08:00:00
3  41487.416667  2013-08-01 09:00:00
4  41487.458333  2013-08-01 10:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                        1.67932e+06
3                                        1.68113e+06
4                                        1.69966e+06

     Unnamed: 3   Unnamed: 4  Unnamed: 5  \
0           NaN          NaN         NaN
1  SIDIROKASTRO         KIPI         NaN
2   2.90658e+06  1.05725e+06         NaN
3    3.1264e+06   1.0584e+06         NaN
4   3.14712e+06  1.05665e+06         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            6836.74
3                                            6770.55
4                                            9042.43

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2      433098              0           85745  ...      8098.4      332368
3      431514              0         82475.2  ...     8983.73      325062
4      430947              0         83112.6  ...     8700.72      319646

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2        447966     8574.17      149052     7339.33          7612.98
3        682450     8091.94      161193     7368.37          2256.99
4        552276     9091.94      145633     9062.64          4494.02

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            9896.88     2478.89     1615.51
3            2934.09     3385.28     1562.22
4            5842.22     3873.33     2143.19

[5 rows x 47 columns]

     Unnamed: 0                 Date  \
0           NaN  2017-03-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                             4396.2
3                                            4360.24
4                                            3463.21

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       1569.53          0         NaN
3       1574.13          0         NaN
4       1574.99          0         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            11.4345
3                                            9.72177
4                                            9.99745

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     422.947        492.385         65.1272  ...     16.1078     314.086
3      421.43        568.819         67.8352  ...     15.9093     282.696
4     420.937        456.022         90.5061  ...     14.3575     283.829

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0      16.775     156.019     15.2139          3.31126
3             0     15.3181     139.878     15.0785          6.51253
4             0     15.3197     147.653      14.661          6.80476

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            5.30464     33.6108     21.4155
3            8.46629     33.1447      19.514
4            8.84619     32.1378     16.1758

[5 rows x 47 columns]
     Unnamed: 0                 Date  \
0           NaN  2017-02-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                             3855.1
3                                            3835.06
4                                            3849.75

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       4514.06    1085.09         NaN
3       4480.83    1082.92         NaN
4       4492.65    1085.34         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                             9.3338
3                                            10.8852
4                                            11.2189

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2      539.11        759.593         85.6178  ...     25.1673     355.393
3      429.16        769.331         85.5528  ...     25.2194     354.629
4     426.465        767.421         87.1007  ...     23.4796     367.231

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2       725.489     17.9075     162.004     19.7184          6.25007
3       771.108     16.3275     175.066     16.8175          4.07719
4         763.6     18.0492     174.469     10.7785          5.18328

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            8.12509     50.3933      39.454
3            5.30034     49.7739      40.011
4            6.73826     49.6697     38.7633

[5 rows x 47 columns]
     Unnamed: 0                 Date  \
0           NaN  2017-12-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 08:00:00
3  41487.416667  2013-08-01 09:00:00
4  41487.458333  2013-08-01 10:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                        1.88435e+06
3                                        1.88445e+06
4                                        2.33827e+06

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2   3.74139e+06     807400         NaN
3   3.41955e+06     805125         NaN
4   3.52553e+06     828877         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            6703.02
3                                            9257.18
4                                            9738.22

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ...   Unnamed: 39 Unnamed: 40  \
0         NaN            NaN             NaN  ...           NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...  MOTOR OIL II      XANTHI
2      432534              0         81441.7  ...        549661     10791.7
3      431134              0         80590.7  ...        507001     13463.3
4      433500              0         77307.5  ...        509522     12092.2

  Unnamed: 41 Unnamed: 42      Unnamed: 43        Unnamed: 44 Unnamed: 45  \
0         NaN         NaN              NaN                NaN         NaN
1    OINOFYTA       PLATY  SALFA ANTHOUSSA  SALFA ANO LIOSSIA      SERRES
2      118038     13619.9          1997.04            2496.31     26095.8
3     97199.5     14305.6          6908.17            8635.22       24845
4       99838     14411.3           3700.2            4625.25     30914.4

  Unnamed: 46    Unnamed: 47 Unnamed: 48
0         NaN            NaN         NaN
1     TRIKALA            NaN         NaN
2     21794.2  120939.019237  752.568419
3     20248.9  143927.814509  572.083672
4     18731.7  194149.809010  468.721463

[5 rows x 49 columns]

     Unnamed: 0                 Date  \
0           NaN  2017-06-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 08:00:00
3  41487.416667  2013-08-01 09:00:00
4  41487.458333  2013-08-01 10:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                        2.24304e+06
3                                         1.9662e+06
4                                             529974

     Unnamed: 3   Unnamed: 4  Unnamed: 5  \
0           NaN          NaN         NaN
1  SIDIROKASTRO         KIPI         NaN
2   2.62146e+06       742178         NaN
3       2506605       929559         NaN
4       2562243  1.09772e+06         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            6554.67
3                                            7845.78
4                                            9921.73

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2      393348         466802         82845.5  ...     9139.86      318304
3      384244         698676         61202.5  ...      9915.4      319995
4      386499         792836         80060.1  ...     9620.92      297048

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2       13932.3     9829.92      133812       15249             3792
3       13761.3     8946.95      123372       16577          3813.01
4       8037.77     9043.64      133700       16567          1745.33

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2             4929.6     2804.63        3986
3            4956.91     3795.66     4032.36
4            2268.93     2520.37     3940.14

[5 rows x 47 columns]
     Unnamed: 0                 Date  \
0           NaN  2017-07-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                            837.826
3                                            838.906
4                                            837.431

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       2621.09          0         NaN
3       2574.21          0         NaN
4       2590.96    225.481         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            1.37395
3                                            2.92499
4                                            2.49485

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     421.029              0         89.3382  ...     14.5132     325.917
3     420.495              0         95.8839  ...     13.7073     269.758
4      421.64              0           89.84  ...     13.9781     267.168

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2       628.871     5.97528      105.23     21.5994          7.72646
3       652.661     6.68167     117.183     16.9245          6.42613
4       433.504     7.58139     127.624     13.6384          2.03234

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            9.27176     13.0142     12.5962
3            7.71136     13.5069     12.4994
4            5.43881     13.0125     9.57943

[5 rows x 47 columns]
     Unnamed: 0                 Date  \
0           NaN  2017-01-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                            3012.85
3                                            3015.11
4                                            2257.99

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       4493.53    1071.24         NaN
3       4489.76    1060.62         NaN
4       4491.81    1059.51         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            1.06423
3                                            1.06331
4                                           0.994068

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     421.656              0         84.2596  ...     9.46238      371.99
3     425.443              0         84.8941  ...     10.6025     362.315
4     424.173              0         90.8693  ...     9.80907     372.904

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2       381.882           0     21.4781     19.2017          0.32286
3       463.748           0     22.0913     17.7329          2.03149
4       636.109     2.53694     21.4803     13.3255           1.3882

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            5.38743     39.5203     30.8267
3            6.43779     39.5625      32.556
4            6.66585     39.4258     41.4618

[5 rows x 47 columns]

     Unnamed: 0                 Date  \
0           NaN  2017-11-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 08:00:00
3  41487.416667  2013-08-01 09:00:00
4  41487.458333  2013-08-01 10:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                             799123
3                                             798160
4                                             824501

     Unnamed: 3   Unnamed: 4  Unnamed: 5  \
0           NaN          NaN         NaN
1  SIDIROKASTRO         KIPI         NaN
2   4.52182e+06  1.02948e+06         NaN
3   4.51875e+06  1.06211e+06         NaN
4   4.49618e+06  1.05956e+06         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            749.797
3                                            1238.41
4                                            822.809

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ...   Unnamed: 39 Unnamed: 40  \
0         NaN            NaN             NaN  ...           NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...  MOTOR OIL II      XANTHI
2      459328         352621           85640  ...        719046     12943.3
3      453690         676578         85060.8  ...        719501     15415.6
4      453358         803451           84084  ...        806725     14303.6

  Unnamed: 41 Unnamed: 42      Unnamed: 43        Unnamed: 44 Unnamed: 45  \
0         NaN         NaN              NaN                NaN         NaN
1    OINOFYTA       PLATY  SALFA ANTHOUSSA  SALFA ANO LIOSSIA      SERRES
2      128946     20692.7          22.7153            29.5299     25448.1
3      152116     21279.4          3222.17            4188.82     27460.6
4      151661     19725.9          12261.3            15939.7       26695

  Unnamed: 46 Unnamed: 47 Unnamed: 48
0         NaN         NaN         NaN
1     TRIKALA         NaN         NaN
2       20521         NaN         NaN
3     21057.4         NaN         NaN
4     18504.7         NaN         NaN

[5 rows x 49 columns]
     Unnamed: 0                 Date  \
0           NaN  2017-09-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 08:00:00
3  41487.416667  2013-08-01 09:00:00
4  41487.458333  2013-08-01 10:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                         4.7007e+06
3                                        4.77382e+06
4                                        4.78315e+06

     Unnamed: 3   Unnamed: 4  Unnamed: 5  \
0           NaN          NaN         NaN
1  SIDIROKASTRO         KIPI         NaN
2             0  1.06535e+06         NaN
3             0  1.06949e+06         NaN
4             0   1.0659e+06         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                             2663.4
3                                            2423.01
4                                            894.155

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2      428610         776964         78743.3  ...      8109.3      404805
3      428249         778100         78663.7  ...     7663.91      394836
4      424877         780656         77922.9  ...      8771.6      393494

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2        363178     8803.33      137822     8476.52          1667.16
3        531289     8751.11      131991     8548.82             4637
4        619423     8498.33      129709     9776.58          3823.47

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            2167.31     2993.61     2813.63
3             6028.1     2389.17     2438.11
4            4970.51     2533.06      2242.7

[5 rows x 47 columns]
../DATA/ENERSHARE_DATA _NTUA/Flows 2014 - Hourly - Excel
     Unnamed: 0                 Date  \
0           NaN  2014-10-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                                  0
3                                                  0
4                                                  0

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       2373.36    522.049         NaN
3       2271.53    408.459         NaN
4       2277.75    407.458         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                           0.386481
3                                           0.454886
4                                            1.69245

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 35 Unnamed: 36  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     428.354        394.189         77.5542  ...     7.13226     311.943
3     426.749        453.548         81.3107  ...     9.25591     312.852
4     424.025        543.635         80.1345  ...     8.78031     324.431

    Unnamed: 37 Unnamed: 38 Unnamed: 39 Unnamed: 40      Unnamed: 41  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     4.65778     129.264     145.612          3.80697
3             0        4.64     126.871     147.025          2.49495
4             0     6.32889     151.185     149.678          6.15324

         Unnamed: 42 Unnamed: 43 Unnamed: 44
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            6.87964     4.72889    0.405318
3            5.73395     4.12444           0
4            8.36258     3.55556           0

[5 rows x 45 columns]

     Unnamed: 0                 Date  \
0           NaN  2014-11-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                                  0
3                                                  0
4                                                  0

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       2902.35    430.029         NaN
3       2805.44    426.638         NaN
4       2790.71    431.935         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                           0.275343
3                                            1.47269
4                                            1.74238

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 35 Unnamed: 36  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     437.532              0         95.1129  ...     10.4747     329.028
3     437.468              0         95.0753  ...     11.9417     323.357
4     435.618              0         96.9707  ...     11.9916     313.161

    Unnamed: 37 Unnamed: 38 Unnamed: 39 Unnamed: 40      Unnamed: 41  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     1.67111     93.4479     157.499          2.02206
3             0     2.98667     90.0807     153.407           7.6931
4      0.139354     3.39556     80.2322     150.481          1.25103

         Unnamed: 42 Unnamed: 43 Unnamed: 44
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            2.42647     27.2356      8.7417
3            9.23172     26.8089     6.50262
4            1.50123     27.0933     5.98658

[5 rows x 45 columns]
     Unnamed: 0                 Date  \
0           NaN  2014-09-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                                  0
3                                                  0
4                                                  0

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       890.668    1082.33         NaN
3       1947.72    1080.31         NaN
4        1974.9    1083.19         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                           0.938994
3                                           0.912423
4                                           0.992769

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 35 Unnamed: 36  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     420.742              0         84.6223  ...     7.13412     257.399
3         419              0         82.5013  ...     9.03851     262.199
4      424.29              0         86.9298  ...      9.0561     282.094

    Unnamed: 37 Unnamed: 38 Unnamed: 39 Unnamed: 40      Unnamed: 41  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     7.60889     98.1788     1.96855          2.13325
3             0     7.32445     111.592    0.430409          4.45904
4             0        7.68     107.995     1.93566          4.48303

         Unnamed: 42 Unnamed: 43 Unnamed: 44
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2              5.705     3.80444    0.572069
3              6.505     13.5822    0.384827
4              6.427     15.0756           0

[5 rows x 45 columns]
     Unnamed: 0                 Date  \
0           NaN  2014-12-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                            1808.29
3                                            1827.12
4                                            1722.46

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       2395.92    268.291         NaN
3       2441.41    225.824         NaN
4       2442.62     209.97         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                                  0
3                                                  0
4                                                  0

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 35 Unnamed: 36  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     431.613              0         106.209  ...     14.0192     250.701
3     430.769              0         105.234  ...     14.3118     278.557
4     430.258              0         105.201  ...     13.4676      296.78

    Unnamed: 37 Unnamed: 38 Unnamed: 39 Unnamed: 40      Unnamed: 41  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     16.5156     133.412     17.1501          5.04365
3        11.935     18.3822     133.998     16.4376          4.27626
4       11.5477     17.2978     142.647     11.4243          4.87561

         Unnamed: 42 Unnamed: 43 Unnamed: 44
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2              7.819     28.9422     16.1535
3              6.826     30.1333     12.8289
4              7.827     30.0978     10.4038

[5 rows x 45 columns]
../DATA/ENERSHARE_DATA _NTUA/Flows 2015 - Hourly - Excel

     Unnamed: 0                 Date  \
0           NaN  2015-06-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                                  0
3                                                  0
4                                                  0

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       1605.27          0         NaN
3       1612.61          0         NaN
4        1644.3          0         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                           0.642769
3                                           0.620284
4                                           0.667546

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 35 Unnamed: 36  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     430.183              0         89.6292  ...      7.2625      297.74
3     429.941              0         84.8459  ...     7.37457     292.647
4     429.248              0         87.0275  ...     7.53588     287.772

    Unnamed: 37 Unnamed: 38 Unnamed: 39 Unnamed: 40      Unnamed: 41  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     3.14667     122.962     10.2468          3.52279
3             0     3.87556     147.471     10.2351          5.22358
4             0     3.21778     151.093      9.9039          3.26712

         Unnamed: 42 Unnamed: 43 Unnamed: 44
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            4.22735    0.746667           0
3            6.26829     12.0622           0
4            3.92055     13.1911           0

[5 rows x 45 columns]
     Unnamed: 0                 Date  \
0           NaN  2015-07-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                                  0
3                                                  0
4                                                  0

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       2214.62     911.85         NaN
3          2103    996.103         NaN
4       1918.21    872.988         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            9.55258
3                                             10.833
4                                            11.0485

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 35 Unnamed: 36  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     430.228              0         50.1946  ...     9.52601     331.464
3     431.602              0         72.1152  ...     9.38053     319.009
4      436.78              0         79.8078  ...     8.94421     320.523

    Unnamed: 37 Unnamed: 38 Unnamed: 39 Unnamed: 40      Unnamed: 41  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     5.03111     127.546     5.77971          2.50637
3             0     6.75556      130.28     1.71548          5.89082
4             0     6.47111     125.897     9.03278          4.01426

         Unnamed: 42 Unnamed: 43 Unnamed: 44
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2              5.217     3.91111    0.673438
3              8.203       13.44     1.38869
4              6.202     14.7556    0.452749

[5 rows x 45 columns]
     Unnamed: 0                 Date  \
0           NaN  2015-03-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                            835.689
3                                            822.728
4                                            829.702

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       1506.21    1087.27         NaN
3       1410.53    1072.12         NaN
4       1347.35    1069.59         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            4.64467
3                                            5.69386
4                                            3.98039

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 35 Unnamed: 36  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     436.065              0          90.019  ...     7.28908     304.576
3     435.768              0         90.8189  ...     6.13468     287.114
4      435.12              0          89.423  ...     5.68275     295.912

    Unnamed: 37 Unnamed: 38 Unnamed: 39 Unnamed: 40      Unnamed: 41  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0       1.808     90.6162     12.2983          4.28978
3             0     2.29333     95.8228     12.3211          2.66209
4             0        3.04     97.3204     12.1146          3.40225

         Unnamed: 42 Unnamed: 43 Unnamed: 44
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2             5.9335     28.8711     17.6524
3             5.0613     29.5822     17.5224
4             5.9123     30.5778     11.0467

[5 rows x 45 columns]

     Unnamed: 0                 Date  \
0           NaN  2015-10-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                                  0
3                                                  0
4                                                  0

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       2587.88    883.443         NaN
3       2777.54    838.287         NaN
4       2839.41     838.92         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            9.83672
3                                            8.23956
4                                            6.14907

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ...   Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...           NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...  MOTOR OIL II      XANTHI
2     437.775              0         93.0557  ...             0     11.6622
3     437.919              0         89.1975  ...             0     12.5156
4     437.983              0         89.7406  ...             0     11.4489

  Unnamed: 39 Unnamed: 40      Unnamed: 41        Unnamed: 42 Unnamed: 43  \
0         NaN         NaN              NaN                NaN         NaN
1    OINOFYTA       PLATY  SALFA ANTHOUSSA  SALFA ANO LIOSSIA      SERRES
2      160.56     84.7836            4.639              6.928     4.12444
3     161.742     69.4273          7.52986              9.931     6.11556
4     158.337     98.0954          3.93495              6.304       13.12

  Unnamed: 44 Unnamed: 45 Unnamed: 46
0         NaN         NaN         NaN
1     TRIKALA         NaN         NaN
2     1.15619         NaN         NaN
3      2.5677         NaN         NaN
4     1.83149         NaN         NaN

[5 rows x 47 columns]
     Unnamed: 0                 Date  \
0           NaN  2015-04-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                            2046.93
3                                             2027.1
4                                            1658.22

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       469.103     837.45         NaN
3       504.034    900.048         NaN
4       707.923    897.282         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            1.14298
3                                            2.26007
4                                            1.64675

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 35 Unnamed: 36  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     428.997              0         90.9022  ...          12      130.28
3     427.752              0         91.8276  ...          11     179.797
4     430.961              0         91.3022  ...          11     271.919

    Unnamed: 37 Unnamed: 38 Unnamed: 39 Unnamed: 40      Unnamed: 41  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     12.7289     136.073     15.1031          5.85128
3             0     16.3733      157.75     15.5787           4.9565
4             0     12.5867     167.467     14.8753           5.0102

         Unnamed: 42 Unnamed: 43 Unnamed: 44
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2              8.594     29.0489     10.3742
3              7.693     28.1956     6.08893
4              7.143     27.0933      2.2742

[5 rows x 45 columns]
     Unnamed: 0                 Date  \
0           NaN  2015-12-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                                  0
3                                                  0
4                                                  0

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       4994.04    1078.04         NaN
3          4816    1080.45         NaN
4       5010.09    1081.56         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            10.1932
3                                            10.7914
4                                            11.1961

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     859.426              0          90.556  ...     15.5326     304.034
3     430.401              0         90.8832  ...     14.3477     291.692
4     430.177              0         94.6286  ...     13.8947     306.754

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     8.40889     140.232     22.2991          10.7136
3             0     8.46222     145.609     21.5727          7.69929
4             0     8.49778     142.451     11.2767          3.55538

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            11.7743       43.52     18.5554
3            9.76588     41.7422     18.6649
4            6.82086     49.0667      16.589

[5 rows x 47 columns]

     Unnamed: 0                 Date  \
0           NaN  2015-05-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                            695.419
3                                              545.2
4                                            517.572

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       1002.02    789.609         NaN
3       1078.33    791.733         NaN
4       974.738    791.201         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            1.03306
3                                           0.721271
4                                           0.700191

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 35 Unnamed: 36  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     435.618              0         93.0148  ...     4.18278     221.285
3     434.935              0         107.726  ...     4.22562     218.656
4     434.509              0          111.14  ...     4.35615     220.738

    Unnamed: 37 Unnamed: 38 Unnamed: 39 Unnamed: 40      Unnamed: 41  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0   0.0711111     86.1641     13.1746        0.0197059
3             0           0     69.6282     13.4285           4.1756
4             0     2.38222     86.3396     13.5876        0.0976999

         Unnamed: 42 Unnamed: 43 Unnamed: 44
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2          0.0236471    0.568889    0.536021
3            5.01072     9.67111           0
4            0.11724     13.2267           0

[5 rows x 45 columns]
     Unnamed: 0                 Date  \
0           NaN  2015-11-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                                  0
3                                                  0
4                                                  0

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       3135.07     226.87         NaN
3       3218.13    269.972         NaN
4       3189.12    276.188         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            2.75558
3                                             1.4231
4                                            1.05423

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     435.237              0         102.344  ...     5.57695     360.194
3       437.5              0         96.9878  ...     5.28821     352.096
4     441.735              0         96.6357  ...     5.52154     340.671

    Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42      Unnamed: 43  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     2.15111     76.1082     19.0105          6.80033
3             0     3.44889     86.2452     14.1892          4.08296
4             0     3.28889     90.5229     14.4938          2.87266

         Unnamed: 44 Unnamed: 45 Unnamed: 46
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2               7.14     23.5378     11.8491
3            5.28715     24.4622     13.1689
4            5.01665          24     13.7781

[5 rows x 47 columns]
     Unnamed: 0                 Date  \
0           NaN  2015-02-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                            1352.28
3                                             1257.5
4                                            1260.48

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       1634.24          0         NaN
3       1508.76          0         NaN
4       1274.63          0         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            1.57989
3                                             2.1471
4                                           0.763117

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 35 Unnamed: 36  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     423.047              0         77.8609  ...     6.40018     1.32294
3     423.191              0         80.0066  ...       6.021           0
4     422.873              0         77.6509  ...       5.572      2.0538

    Unnamed: 37 Unnamed: 38 Unnamed: 39 Unnamed: 40      Unnamed: 41  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     1.99111     85.7027     13.0926          4.05607
3             0     2.16889     91.1772     12.9562          3.51562
4             0        1.76     79.7258     12.9446         0.022459

         Unnamed: 42 Unnamed: 43 Unnamed: 44
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            4.86729     26.2756     20.1208
3            4.21875     24.4978     17.3061
4          0.0269508     24.3911      16.571

[5 rows x 45 columns]

     Unnamed: 0                 Date  \
0           NaN  2015-09-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                                  0
3                                                  0
4                                                  0

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       1650.81     1079.8         NaN
3       2029.86    1076.69         NaN
4       2946.13    1079.35         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                           0.738983
3                                             2.0935
4                                            1.57721

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 35 Unnamed: 36  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     431.703              0         91.3946  ...     8.07292      191.09
3     430.479              0         90.8783  ...      7.4877     198.153
4     430.172              0         95.7136  ...     7.79823     216.065

    Unnamed: 37 Unnamed: 38 Unnamed: 39 Unnamed: 40      Unnamed: 41  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2       732.836     6.16889      117.31     10.8821          7.12007
3        748.08     6.20444     125.345     10.8076          6.99803
4       744.687     6.95111     142.935     10.9439          3.44433

         Unnamed: 42 Unnamed: 43 Unnamed: 44
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            8.54409     4.30222     1.13414
3            8.39764     4.55111     1.71028
4            4.13319     3.80444     10.0673

[5 rows x 45 columns]
     Unnamed: 0                 Date  \
0           NaN  2015-01-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                            1.86764
3                                                  0
4                                            219.046

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       2364.74    782.328         NaN
3       2397.38    512.001         NaN
4       2438.46    513.324         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                           0.136442
3                                           0.137161
4                                          0.0921605

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 35 Unnamed: 36  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     435.095              0         90.9743  ...     11.1896           0
3     433.904              0         95.3129  ...     11.1699           0
4     433.683              0         95.1789  ...     10.9345      9.3649

    Unnamed: 37 Unnamed: 38 Unnamed: 39 Unnamed: 40      Unnamed: 41  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     3.11111     32.4378     22.0459          5.06585
3             0    0.497778     33.9043     24.1939          3.63352
4             0     2.18667     33.7282     23.5737        0.0480136

         Unnamed: 42 Unnamed: 43 Unnamed: 44
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            6.07902        43.2     36.4957
3            4.36022     42.8444     41.0441
4          0.0576163       43.68     38.4149

[5 rows x 45 columns]
     Unnamed: 0                 Date  \
0           NaN  2015-08-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 09:00:00
3  41487.416667  2013-08-01 10:00:00
4  41487.458333  2013-08-01 11:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                                  0
3                                                  0
4                                                  0

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2       3889.83     1063.8         NaN
3       3449.23    1064.14         NaN
4       3084.63    1065.61         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(MWh / Combustion Reference Temperature 0oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            1.10514
3                                            1.02967
4                                            2.60358

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 35 Unnamed: 36  \
0         NaN            NaN             NaN  ...         NaN         NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...       SPATA   MOTOR OIL
2     415.642              0         85.2398  ...     7.98459     311.986
3     415.666              0         89.9418  ...     7.22451      279.62
4     416.216              0         94.0415  ...     7.53185     274.958

    Unnamed: 37 Unnamed: 38 Unnamed: 39 Unnamed: 40      Unnamed: 41  \
0           NaN         NaN         NaN         NaN              NaN
1  MOTOR OIL II      XANTHI    OINOFYTA       PLATY  SALFA ANTHOUSSA
2             0     2.91556     89.5312     10.4783          1.82324
3             0     2.20444     79.9489     10.3676          4.09704
4             0     1.58222     108.769     10.6022          2.36803

         Unnamed: 42 Unnamed: 43 Unnamed: 44
0                NaN         NaN         NaN
1  SALFA ANO LIOSSIA      SERRES     TRIKALA
2            2.18788     1.74222           0
3            4.91644     2.48889           0
4            2.84163        1.92           0

[5 rows x 45 columns]
../DATA/ENERSHARE_DATA _NTUA/Flows 2021 - Hourly - Excel - Missing data

     Unnamed: 0           Ημερομηνία  \
0           NaN  2021-08-23 00:00:00
1           NaN                  Ωρα
2  44431.333333  2021-08-23 08:00:00
3  44431.375000  2021-08-23 09:00:00
4  44431.416667  2021-08-23 10:00:00

  Σχετικά Σημεία Εισόδου\nΠοσότητα Παράδοσης Φ.Α.\n(KWh / Θερμοκρασία καύσης αναφοράς 25°C)  \
0                                                NaN
1                                        ΑΓΙΑ ΤΡΙΑΔΑ
2                                        1.91207e+06
3                                        2.12729e+06
4                                        2.23955e+06

     Unnamed: 3 Unnamed: 4   Unnamed: 5  Unnamed: 6  \
0           NaN        NaN          NaN         NaN
1  ΣΙΔΗΡΟΚΑΣΤΡΟ      ΚΗΠΟΙ          TAP         NaN
2   3.85254e+06          0  1.51905e+06         NaN
3   4.56875e+06          0  1.50855e+06         NaN
4   4.58477e+06          0  1.50312e+06         NaN

  Σχετικά Σημεία Εξόδου\nΠοσότητα Παραλαβής Φ.Α.\n(KWh / Θερμοκρασία καύσης αναφοράς 25°C)  \
0                                                NaN
1                                     ΑΓΙΟΙ ΘΕΟΔΩΡΟΙ
2                                            157.071
3                                            183.242
4                                            416.491

   Unnamed: 8     Unnamed: 9  ... Unnamed: 245 Unnamed: 246 Unnamed: 247  \
0         NaN            NaN  ...          NaN          NaN          NaN
1  ΑΛΟΥΜΙΝΙΟΝ  ΑΛΟΥΜΙΝΙΟΝ ΙΙ  ...          NaN          NaN          NaN
2      416550              0  ...          NaN          NaN          NaN
3      416533              0  ...          NaN          NaN          NaN
4      416718              0  ...          NaN          NaN          NaN

  Unnamed: 248 Unnamed: 249 Unnamed: 250 Unnamed: 251 Unnamed: 252  \
0          NaN          NaN          NaN          NaN          NaN
1          NaN          NaN          NaN          NaN          NaN
2          NaN          NaN          NaN          NaN          NaN
3          NaN          NaN          NaN          NaN          NaN
4          NaN          NaN          NaN          NaN          NaN

  Unnamed: 253 Unnamed: 254
0          NaN          NaN
1          NaN          NaN
2          NaN          NaN
3          NaN          NaN
4          NaN          NaN

[5 rows x 255 columns]
     Unnamed: 0                 Date  \
0           NaN  2021-12-12 00:00:00
1           NaN                 Time
2  44434.333333  2021-08-26 08:00:00
3  44434.375000  2021-08-26 09:00:00
4  44434.416667  2021-08-26 10:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                        2.59191e+06
3                                        2.18744e+06
4                                        2.18952e+06

     Unnamed: 3 Unnamed: 4     Unnamed: 5  Unnamed: 6  \
0           NaN        NaN            NaN         NaN
1  SIDIROKASTRO       KIPI  NEA MESIMVRIA         NaN
2     3.268e+06          0    1.68525e+06         NaN
3       2923204          0    1.67958e+06         NaN
4       2924687          0     1.6799e+06         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            511.495
3                                            490.227
4                                            504.302

   Unnamed: 8     Unnamed: 9  ... Unnamed: 245 Unnamed: 246 Unnamed: 247  \
0         NaN            NaN  ...          NaN          NaN          NaN
1  ALOYMINION  ALOYMINION II  ...          NaN          NaN          NaN
2      425019              0  ...          NaN          NaN          NaN
3      428976              0  ...          NaN          NaN          NaN
4      428997              0  ...          NaN          NaN          NaN

  Unnamed: 248 Unnamed: 249 Unnamed: 250 Unnamed: 251 Unnamed: 252  \
0          NaN          NaN          NaN          NaN          NaN
1          NaN          NaN          NaN          NaN          NaN
2          NaN          NaN          NaN          NaN          NaN
3          NaN          NaN          NaN          NaN          NaN
4          NaN          NaN          NaN          NaN          NaN

  Unnamed: 253 Unnamed: 254
0          NaN          NaN
1          NaN          NaN
2          NaN          NaN
3          NaN          NaN
4          NaN          NaN

[5 rows x 255 columns]
../DATA/ENERSHARE_DATA _NTUA/Flows 2018 - Hourly - Excel
     Unnamed: 0                 Date  \
0           NaN  2018-01-01 00:00:00
1           NaN                 Time
2  41487.375000  2013-08-01 08:00:00
3  41487.416667  2013-08-01 09:00:00
4  41487.458333  2013-08-01 10:00:00

  Relative Entry Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)  \
0                                                NaN
1                                        AGIA TRIADA
2                                             807434
3                                             806003
4                                             805877

     Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0           NaN        NaN         NaN
1  SIDIROKASTRO       KIPI         NaN
2   3.73611e+06     366215         NaN
3   3.64613e+06     317731         NaN
4   3.62793e+06     313787         NaN

  Relative Exit Points\nN.G. Delivery Quantity\n(kWh / Combustion Reference Temperature 25oC)  \
0                                                NaN
1                                    AGIOI THEODOROI
2                                            659.459
3                                            666.151
4                                            632.487

   Unnamed: 7     Unnamed: 8      Unnamed: 9  ... Unnamed: 152 Unnamed: 153  \
0         NaN            NaN             NaN  ...          NaN          NaN
1  ALOYMINION  ALOYMINION II  ALOYMINION III  ...          NaN          NaN
2      448028         488242         86359.4  ...          NaN          NaN
3      447342         532260         85753.7  ...          NaN          NaN
4      447781         405131         85847.8  ...          NaN          NaN

  Unnamed: 154 Unnamed: 155 Unnamed: 156 Unnamed: 157 Unnamed: 158  \
0          NaN          NaN          NaN          NaN          NaN
1          NaN          NaN          NaN          NaN          NaN
2          NaN          NaN          NaN          NaN          NaN
3          NaN          NaN          NaN          NaN          NaN
4          NaN          NaN          NaN          NaN          NaN

  Unnamed: 159 Unnamed: 160 Unnamed: 161
0          NaN          NaN          NaN
1          NaN          NaN          NaN
2          NaN          NaN          NaN
3          NaN          NaN          NaN
4          NaN          NaN          NaN

[5 rows x 162 columns]

KeyboardInterrupt:

In [16]:
#Code for reading of only one excel file
import os
import pandas as pd
import datetime

# This code reads from a specific excel file all sheets and merges the date with time and drops useless columns
filename = '/home/billys/Documents/Διπλωματική/DATA/ENERSHARE_DATA _NTUA/Flows 2015 - Hourly - Excel/Hourly-Flows-01_2015.xls'
dfs_dict = pd.read_excel(filename, sheet_name=None, engine='xlrd')
print("The number of sheets in this excel file is", len(dfs_dict))
print(dfs_dict.keys())
prev_df = pd.DataFrame()
result = pd.DataFrame()
for df in dfs_dict.values():
    df.columns = df.iloc[1]
    
    for i in range(2, len(df['Time'])):
        if type(df['Time'][i]) is datetime.datetime:
            df['Time'][i] = datetime.datetime.combine(df['Time'][0].date(), df['Time'][i].time())
    df = df.iloc[2:26, 1:]
    
    result = pd.concat([prev_df, df], ignore_index=True)
    prev_df = result

print(result)

The number of sheets in this excel file is 31
dict_keys(['01.01.2015', '02.01.2015', '03.01.2015', '04.01.2015', '05.01.2015', '06.01.2015', '07.01.2015', '08.01.2015', '09.01.2015', '10.01.2015', '11.01.2015', '12.01.2015', '13.01.2015', '14.01.2015', '15.01.2015', '16.01.2015', '17.01.2015', '18.01.2015', '19.01.2015', '20.01.2015', '21.01.2015', '22.01.2015', '23.01.2015', '24.01.2015', '25.01.2015', '26.01.2015', '27.01.2015', '28.01.2015', '29.01.2015', '30.01.2015', '31.01.2015'])

/home/billys/.local/lib/python3.6/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

1                   Time AGIA TRIADA SIDIROKASTRO     KIPI  NaN  \
0    2015-01-01 09:00:00     1.86764      2364.74  782.328  NaN
1    2015-01-01 10:00:00           0      2397.38  512.001  NaN
2    2015-01-01 11:00:00     219.046      2438.46  513.324  NaN
3    2015-01-01 12:00:00     738.346      2438.65  513.631  NaN
4    2015-01-01 13:00:00     715.792      2462.36  512.974  NaN
..                   ...         ...          ...      ...  ...
739  2015-01-31 04:00:00     1768.63      1629.47        0  NaN
740  2015-01-31 05:00:00     1775.48      1639.24        0  NaN
741  2015-01-31 06:00:00     1768.13      1659.02        0  NaN
742  2015-01-31 07:00:00     1782.08      1671.58        0  NaN
743  2015-01-31 08:00:00     1784.77      1652.11        0  NaN

1   AGIOI THEODOROI ALOYMINION ALOYMINION II ALOYMINION III   ATHENS  ...  \
0          0.136442    435.095             0        90.9743  1022.78  ...
1          0.137161    433.904             0        95.3129  964.889  ...
2         0.0921605    433.683             0        95.1789  909.655  ...
3         0.0933327    434.947             0        90.6915  946.129  ...
4          0.146365    436.569             0        90.0832  1090.82  ...
..              ...        ...           ...            ...      ...  ...
739        0.113794    422.186             0        82.3101  241.832  ...
740         1.10098    421.428             0        83.9954  240.088  ...
741         2.59893    421.301             0        82.2137  256.186  ...
742        0.992284    421.592             0        83.1517   369.37  ...
743               0    423.077             0         77.512  509.124  ...

1      SPATA MOTOR OIL MOTOR OIL II    XANTHI OINOFYTA    PLATY  \
0    11.1896         0            0   3.11111  32.4378  22.0459
1    11.1699         0            0  0.497778  33.9043  24.1939
2    10.9345    9.3649            0   2.18667  33.7282  23.5737
3    11.1816   25.0155            0  0.604444  33.2008  22.2877
4    9.84795   2.58689            0   2.61333   33.894  20.1344
..       ...       ...          ...       ...      ...      ...
739   7.0627         0            0   2.64889  109.256   12.888
740  6.73343         0            0   3.32444  93.9685  13.1835
741  6.90467         0            0      2.88  88.4709  12.9348
742  6.36038   23.2564            0   2.79111  92.2171  12.9419
743  6.54159   5.02227            0   2.22222  82.0395  13.1382

1   SALFA ANTHOUSSA SALFA ANO LIOSSIA   SERRES  TRIKALA
0           5.06585           6.07902     43.2  36.4957
1           3.63352           4.36022  42.8444  41.0441
2         0.0480136         0.0576163    43.68  38.4149
3           1.70794           2.04953  44.3022  35.5121
4            2.7108           3.25296  44.6578  34.5842
..              ...               ...      ...      ...
739         1.26389           1.51667  34.1333  9.19587
740        0.405599          0.486719  31.6444  9.10032
741         6.76081           8.11297  29.1556  10.2563
742         4.81906           5.78287  26.9511  11.6964
743          3.9933           4.79196  26.8089  16.5374

[744 rows x 44 columns]

In [ ]:
#Code for reading all excel files together and merging them into one dataframe
import os
import pandas as pd
import datetime

#Choose your own folder path in order to open it
folder_path = '../DATA/ENERSHARE_DATA _NTUA'
prefix = 'Flows'

# Open all folders that start with 'Flows'
i = 0
prev_df = pd.DataFrame()
result = pd.DataFrame()
print(os.listdir(folder_path))
for foldername in os.listdir(folder_path):
    if foldername.startswith(prefix):
        file_path = folder_path
        file_path = os.path.join(folder_path, foldername)
        # Open all excel files from those folders
        for filename in os.listdir(file_path):
            print(filename)
            i = i + 1
            temp_filename = os.path.join(file_path, filename)
            dfs_dict = pd.read_excel(temp_filename, engine='xlrd' if filename.endswith('.xls') else 'openpyxl', sheet_name=None)
            for df in dfs_dict.values():
                df.columns = df.iloc[1]

                for i in range(2, len(df['Time'])):
                    if type(df['Time'][i]) is datetime.datetime:
                        df['Time'][i] = datetime.datetime.combine(df['Time'][0].date(), df['Time'][i].time())
                df = df.iloc[2:26, 1:]

                result = pd.concat([prev_df, df], ignore_index=True)
                prev_df = result

print(result)

Hourly-Flows-05_2016.xls

/home/billys/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Hourly-Flows-09_2016-1.xls
Hourly-Flows-04_2016.xls
Hourly-Flows-01_2016.xls
Hourly-Flows-12_2016.xls
Hourly-Flows-02_2016-1.xls
Hourly-Flows-06_2016-2.xls
Hourly-Flows-03_2016.xls
Hourly-Flows-08_2016.xls
Hourly-Flows-10_2016.xls
Hourly-Flows-07_2016.xls
Hourly-Flows-10_2017.xlsx